[package]
name = "starknet_hello_world"
version = "0.1.0"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.5.0"

[lib]
sierra = true
casm = true

[[target.starknet-contract]]
sierra = true
casm = true